apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fpesuvbb9-nodejs-gitops
  description: This is GitOps manifest for fpesuvbb9-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=fpesuvbb9-nodejs
    backstage.io/kubernetes-id: fpesuvbb9-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fpesuvbb9-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fpesuvbb9-nodejs
