apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fpesuvbb9-nodejs
  janus-idp.io/tekton: fpesuvbb9-nodejs
  backstage.io/kubernetes-id: fpesuvbb9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fpesuvbb9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
